### ISSUE TITLE
GeoJSON component takes around 15 seconds to render a FeatureCollection object with around 16000 Feature objects. Same data is rendered by leaflet js in 1.2 seconds

### ISSUE THREAD

**Issue by AtulKekan-developer** [PaulLeCam/react-leaflet#1020]
GeoJSON component takes around 15 seconds to render a FeatureCollection object with around 16000 Feature objects.
Leaflet js takes 1.2 seconds to render the same amount of data
Why does GeoJSON component take so much time ?

![image](https://user-images.githubusercontent.com/70166263/185087887-12295614-aba1-4e8d-acaf-f1727a5c3c24.png)

Above image is time taken by leaflet js

![image](https://user-images.githubusercontent.com/70166263/185088028-b5568d7d-9047-4246-a53b-b945ec32d0b7.png)

Above image is time taken by GeoJSON component

Please suggest me a solution to improve rendering time using react-leaflet GeoJSON component

**Comment by nizz0k** [comment]
Hi, so basic leaflet creates individual dom elements for marker, which means that browsers start to see major performance hits at more than a few hundred markers. The solution to this is to use one of 2 work arounds: 

1. The basic circle marker can be natively rendered to a canvas element, rather than as a a div. You can do this by setting the renderer to the canvas option.
2. There are libraries which also provide the canvas functionality, but the one I've been using in my app seems to have broken on me.

Otherwise, it says in the docs that the issue queue isn't meant to be used from support; you're just lucky I happened to be digging for a solution to my library issues...

**Comment by javalonde** [comment]
Hi,
I am struggling with a similar issue.
Slower rendering times are acceptable, but the problem is that everything freezes during this time.
Is there any way to avoid this?

**Comment by AtulKekan-developer** [comment]
> Hi, so basic leaflet creates individual dom elements for markers, which means that browsers start to see major performance hits at more than a few hundred markers. The solution to this is to use one of 2 work arounds:
> 
> 1. The basic circle marker can be natively rendered to a canvas element, rather than as a a div. You can do this by setting the renderer to the canvas option on your map container.
> 2. There are libraries which also provide the canvas functionality, but the one I've been using in my app seems to have broken on me.
> 
> Otherwise, it says in the docs that the issue queue isn't meant to be used from support; you're just lucky I happened to be digging for a solution to my library issues...

Hi @nizz0k  can you please mention the name of the libraries that provide canvas functionality

**Comment by AtulKekan-developer** [comment]
> Hi, I am struggling with a similar issue. Slower rendering times are acceptable, but the problem is that everything freezes during this time. Is there any way to avoid this?

@javalonde  i face the freezing issue too

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
