### ISSUE TITLE
onLeafletLoad="handler" is not firing in main Map element.

### ISSUE THREAD

**Issue by bartekupartek** [PaulLeCam/react-leaflet#105]
There is no `idle` event in leaflet, so I have to call once `onLoad` and then `onMoveend` to get and set in redux always actual map bounds, but `onLoad` map event is not fired, as I can see on leaflet issues it is triggered when `map.setView()`, is it possible to do it with react-leaflet?

`<Map onLeafletLoad={this.plotViewPoint} id="map-container" ref='map' center={position} zoom={13} onLeafletMoveend={this.plotViewPoint}>`

By the way it is fired in `<TileLayer onLeafletLoad={this.plotViewPoint} ...>` but event target doesn't contains `.map` in main tree object like in `onMoveend` and I will not to make
`const map = e.target._map || e.target;`

**Comment by bartekupartek** [comment]
I found solution, instead of invoking onLeafletLoad i can get map bounds after componentDidMount:
```
componentDidMount() {
  this.mapApi = this.refs.map.leafletElement; // <= this is the Leaflet Map object
  let bounds = this.mapApi.getBounds();
},
```

**Comment by PaulLeCam** [comment]
Hi,
Sorry for the late reply.

It's likely the "load" event is not fired because the map is already loaded when the listener is added, but as you've done in your solution, you can access the `leafletElement` created for the `<Map>` in its children, because the children are only rendered after the instance is created.
