### ISSUE TITLE
How to custom the request header in TileLayer ? 

### ISSUE THREAD

**Issue by IHsunChen** [PaulLeCam/react-leaflet#1080]
I have searched google and did not find any usable answer.
Can someone help me ?

**Comment by AhXianGL** [comment]
From the source code perspective of LeafLet Tilelayer, which extends Gridlayer, the tileLayer request is sent via the img HTML tag with its src property as the request's url.
you can create a class extends the tileLayer and overridesTileLayer's [`createTile()`](https://github.com/Leaflet/Leaflet/blob/b6b56f6e707142c177fad2f67827a5007e56736a/src/layer/tile/TileLayer.js#L145).
You're trying to do X, and you thought of solution Y. So you're asking about solution Y, without even mentioning X. The problem is, there might be a better solution, but we can't know that unless you describe what X is, see ("X Y problem")[https://www.perlmonks.org/?node=XY+Problem]
