### ISSUE TITLE
[Turbopack] Parsing css source code failed

### ISSUE THREAD

**Issue by rwieruch** [PaulLeCam/react-leaflet#1122]
## Bug report in v4

https://github.com/vercel/turbo/issues/2356#issuecomment-1853302120

Trying to use Turbopack in Next.js with the latest Leaflet/Leaflet-React version yields the error from the linked Issue. A Turbopack maintainer mentioned that Leaflet does not use valid syntax here.

**Comment by jpainam** [comment]
Is t here any update for this issue? @rwieruch  How did you solve it?
Thanks

**Comment by rwieruch** [comment]
Did not solve it. Cannot use Turbopack until this is fixed :)

**Comment by rwieruch** [comment]
Related https://github.com/vercel/turbo/issues/2356#issuecomment-1945068331

**Comment by rinvii** [comment]
I'm getting a similar error

![Screen Shot 2024-03-12 at 8 28 35 AM](https://github.com/PaulLeCam/react-leaflet/assets/76126859/0ba7f455-5235-464a-aafb-332501fadc2d)

**Comment by shenst1** [comment]
@rwieruch I was able to do a workaround using the cdn:

```
Map.tsx
import "./Map.css";
```

```
Map.css
@import url('https://unpkg.com/leaflet@1.9.4/dist/leaflet.css');
```

**Comment by mattmchugh4** [comment]
I was unable to reproduce this issue mentioned. My setup includes the following versions:

- **Next.js**: 14.2.5
- **Leaflet**: 1.9.4
- **React-Leaflet**: 4.2.1
- **React**: 18
- **Turbopack**: used with `next dev --turbo`

Everything seems to be working fine, and the Leaflet CSS is being bundled without any errors.

If there was an issue, it appears it might have been related to the default Leaflet CSS. According to the [vercel/turborepo#2356 (comment)](https://github.com/vercel/turborepo/issues/2356#issuecomment-1945068331), the problem might have been caused by old CSS in Leaflet that's since been removed or updated.

Given that I don't see the issue occurring, I think this should be closed. However, if anyone encounters the problem again, please list your dependencies / provide an example.

**Comment by wfl-junior** [comment]
I am having the same issue with the library `cmdk`

- Next.js: 15.0.0
- cmdk: 1.0.0
- React: 19.0.0-rc-65a56d0e-20241020
- Turbopack: used with `next dev --turbo`

![image](https://github.com/user-attachments/assets/2fbbaea4-d23b-4bc2-ad0e-0cb80fd68c2d)

**Comment by yunusozcan** [comment]
Resolved my issue with importing an external package that includes a CSS file  by following Next.js's package bundling optimization guidelines: 
https://nextjs.org/docs/app/building-your-application/optimizing/package-bundling#optimizing-package-imports
```
import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  /* config options here */
    experimental: {
        optimizePackageImports: [''],
    },
};

export default nextConfig;
```
