### ISSUE TITLE
Please provide example for featureGroup

### ISSUE THREAD

**Issue by scherler** [PaulLeCam/react-leaflet#14]
Hi Paul, 

I am ATM looking into using FeatureGroup because I am integrating Leaflet.draw. I am trying to understand how I can pass my different shapes that I have saved into the featureGroup.

For example imagine I have the following: 

    <Marker position={position}/>
    <Rectangle bounds={bounds}>

how would I add them into the FeatureGroup?

**Comment by PaulLeCam** [comment]
Hi,

I have never used FeatureGroup, I just added it as an interface to http://leafletjs.com/reference.html#featuregroup so that you can pass it a `layer` array, that would be Leaflet elements.

It would really make sense to be able to have React-Leaflet elements as children, but I don't know how it would behave with Leaflet, so for now it's not supported.
