### ISSUE TITLE
Use context instead of cloneElement?

### ISSUE THREAD

**Issue by mgmeyers** [PaulLeCam/react-leaflet#150]
Hello! I've been using `react-leaflet` a lot lately and have been thinking about various ways to improve performance.

Have you considered using React's `context` functionality to pass the `map` / `layerContainer` objects to child components? It would greatly reduce the number of iterations per render (especially when rendering large amounts of map layers), which could offer a performance boost.

https://facebook.github.io/react/docs/context.html

Unfortunately the API isn't stable yet, but I thought I may as well bring it up and see if you had any thoughts. Could it potentially be worth the dealing with future breaking changes?

**Comment by PaulLeCam** [comment]
Yes, it's probably a good idea!
From my understanding the context API is pretty stable for a basic use case, the issue is more about overriding keys in children.

A possible way to abstract it in this lib would be to create getters like `getMap()`, `getLayerContainer()` etc. that could either get the value from the `context` (new behavior) or the `props` (legacy behavior), so the transition could be smoother.
Eventually if the context API is no longer relevant, the internals of the lib could also change as long as the getters are consistent.

**Comment by mgmeyers** [comment]
Great idea. I'll take a crack it and see what I can come up with.

**Comment by PaulLeCam** [comment]
Now implemented in v0.12.
