### ISSUE TITLE
Issue with large dataset

### ISSUE THREAD

**Issue by patrickml** [PaulLeCam/react-leaflet#158]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] Check that all peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Check that you are using a supported version of React (v0.14 or v15).
- [x] Check that you are using a supported version of Leaflet (v.0.7)
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md#technical-considerations).

### Expected behavior
Load 10k markers onto a map of the united states

### Actual behavior
Browser freezing and crashing

### Steps to reproduce
Load a 10k data set
```
const MAP = ({ suppliers }) => (
  <Map center={[37.09, -95.71]} zoom={4}>
    <TileLayer
      url="http://{s}.tile.osm.org/{z}/{x}/{y}.png"
      attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
    />
    {
      suppliers.map((supplier, index) => (
        <Marker position={[supplier.LATITUDE, supplier.LONGITUDE]} key={index} />
      ))
    }
  </Map>
);
```

Here is a fiddle https://jsfiddle.net/68442vy5/3/ be warned it will crash your tab on chrome

**Comment by PaulLeCam** [comment]
Hi,
Sorry but it's not something I'm going to investigate this, as needing 10k markers to be visible is likely to be a very rare edge case.
Future changes notably by using context instead of props as suggested in [this issue](https://github.com/PaulLeCam/react-leaflet/issues/150) would likely improve the performance of this lib, but no matter what it is an abstraction on top of Leaflet and therefore comes as a certain cost.

Regarding your use case, do you absolutely need to have all these markers visible rather than reducing them to the visible bounds?

**Comment by kujon** [comment]
👍 10k may be an edge case, but the performance starts to suffer around 500 markers already. Go over 1/2k and the map is barely usable.

**Comment by patrickml** [comment]
@PaulLeCam instead od loading markers I ended up creating polygons to over an area -- I really just needed to map the data to see overlapping areas. Marker/Popups were really just nice to view the data.

Thank you for your time. @kujon Thank you for letting me know about the 500 limit before performance tanking. I will keep that in mind for future projects.
