### ISSUE TITLE
Flux example ?

### ISSUE THREAD

**Issue by moimael** [PaulLeCam/react-leaflet#16]
Hi,

I started to use your react-leaflet component (works well for now :)) and wanted to know how to integrate it with react + flux. How should the state be handled  ? Creating a separate store for leaflet (which feels weird since leaflet handle his own state) ? Do you provide any convenient method to be able to separate state from view ?

Thanks !

**Comment by luqmaan** [comment]
I'm using react-leaflet with Flux here
https://github.com/luqmaan/instabus-react/

**Comment by luqmaan** [comment]
I use react-leaflet mainly here: https://github.com/luqmaan/instabus-react/blob/master/client/js/components/MapSection.react.jsx

I need to use some Leaflet plugins like https://github.com/Leaflet/Leaflet.label, so I had to copypasta the source for Marker and modify its `componentWillMount`: https://github.com/luqmaan/instabus-react/blob/master/client/js/components/StopMarker.react.jsx#L22-L30.

My app displays transit data, so I need to use polylines and markers to display vehicles and stops along a route. I have a StopStore, VehicleStore, RouteStore and PolylineStore: https://github.com/luqmaan/instabus-react/blob/master/client/js/stores/. 

![image](https://cloud.githubusercontent.com/assets/1275831/6669521/5fa986b0-cbc7-11e4-908a-859bf323de57.png)

**Comment by moimael** [comment]
Your example is really helpful thanks ! 

I'm still unsure how to call method on map itself. For example, what if I want to call locate on my instance of Leaflet.Map ? 
Where should I do it ? 

I understand the way flux works, but with third-party component which include their own state and event system, I really have a hard time figuring out how to cleanly integrate them.

**Comment by PaulLeCam** [comment]
Hi!

Really depends on your use case, but if you are using Flux, your components should simply render the state of the app, not hold it.
There is no major difference using React-Leaflet or components manipulating the DOM, all you need to do is listen to events, dispatch actions, handle your state in the stores and render your components based on their state.

You can have a look at the ["events" example](https://github.com/PaulLeCam/react-leaflet/blob/master/example/events.js) that listens to an event on the map to update its own state. Using Flux, it would dispatch an action instead of setting its state directly, and get its state from the related store.

**Comment by moimael** [comment]
Thanks a lot ! It's starting to take shape :)
