### ISSUE TITLE
Problems with findComponentRoot

### ISSUE THREAD

**Issue by Otann** [PaulLeCam/react-leaflet#18]
Hi!

I have some weird error, while using your lib.
I wonder if it is possible to use your components inside old-style react createClass components?

When I use simple component everything seems to work fine:

```jsx
import React from 'react'

// import {Map, Marker, Popup, TileLayer} from "react-leaflet";

module.exports = React.createClass({
  displayName: 'Satellite',

  render: function() {
    const position = [this.state.lat, this.state.lng];
    return (
      <h1>content</h1>
    );
  },

  getInitialState: function() {
    return {
      lat: 51.505,
      lng: -0.09,
      zoom: 13
    };
  }

});
```

But then I add simple map from your example:

```jsx
import React from 'react'

import { Map, Marker, Popup, TileLayer } from 'react-leaflet';

module.exports = React.createClass({
  displayName: 'Satellite',

  render: function() {
    const position = [this.state.lat, this.state.lng];
    return (
      <Map center={position} zoom={this.state.zoom}>
        <TileLayer
          url="http://{s}.tile.osm.org/{z}/{x}/{y}.png"
          attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
        />
        <Marker position={position}>
          <Popup>
            <span>A pretty CSS3 popup. <br/> Easily customizable.</span>
          </Popup>
        </Marker>
      </Map>
    );
  },

  getInitialState: function() {
    const flux = this.getFlux();
    flux.actions.drafts.reloadAsync();
    return {
      lat: 51.505,
      lng: -0.09,
      zoom: 13
    };
  }

});
```

And I have following error in browser:

```
Error: Invariant Violation: findComponentRoot(..., .0.0.0.$=11:0.$=10:0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.
```

Am I forgetting about something or doing something wrong?

**Comment by PaulLeCam** [comment]
Hi,

Yes it's possible to use it with `React.createClass()`, as long as it's using React 0.13+ the components definitions will be handled by React.

Looking at your code, how does it behave when you remove these lines?
```js
const flux = this.getFlux();
flux.actions.drafts.reloadAsync();
```

**Comment by PaulLeCam** [comment]
Hi @Otann, any news on this?

**Comment by Otann** [comment]
Sorry, I've lost track of this.
I've decided to switch back to react 0.12 anyway, because Fluxxor does not work with 0.13.
I suggest to close this, in case I will encounter this issue again, I will notify you.

**Comment by Oustad** [comment]
Hi, I've seem to have run into the same issue as the orignal poster here.

`Uncaught (in promise) Error: Invariant Violation: findComponentRoot(..., .0.1.0.$/vessel/922.2.1.0.0.0.$=11:0.$=10:0): Unable to find element.`



    return (
             <Map ref map center={this.props.lastPosition} zoom={5}>
              <TileLayer
                url='http://{s}.tile.stamen.com/toner/{z}/{x}/{y}.png'
                attribution='Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>'
              />
              <Marker position={this.props.lastPosition} title={this.props.name} alt={this.props.name}>
                  <Popup>
                    <span>{this.props.name}</span>
                </Popup>
              </Marker>
            </Map>
    );

From debugging it looks like the problem is happening in the following line of html

`<noscript data-reactid=".0.1.0.$/vessel/922.2.1.0.0.0.$=11:0">&lt;noscript data-reactid=".0.1.0.$/vessel/922.2.1.0.0.0.$=11:0.$=10:0"&gt;</noscript>`

It also only happens when I use the Popup tag inside of the marker and for some reason it seems to only happen when I also render some charts on the page, in a different component, but with the same parent node. If I remove either the popup or the charts, the error do not occur.

I'm using ES6 classes for the components and flummox as flux implementation.

**Comment by Oustad** [comment]
Problem seems to originate from 
https://github.com/PaulLeCam/react-leaflet/blob/master/src/PopupContainer.js#L10
Changing the tag to anything other than noscript, will make the error go away.

**Comment by PaulLeCam** [comment]
Hi,

Hard to tell what the problem is without seeing more code, but could you please try without flummox and other components?
It's possible they try to update the component before it's actually mounted, and that would likely result in the error thrown by React.

**Comment by Frikki** [comment]
The problem also occurs when using the browser navigation’s back and forward. It is definitely to the `PopUpContainer`, as removing it causes the error not to be thrown. Tested without flummox.

**Comment by PaulLeCam** [comment]
Hi,

I've been investigating a bit on this and I think the issue is that you are updating the Popup, which is simply not supported.

One thing to understand with this lib is that the DOM is manipulated by Leaflet, not React, so there is no use of virtual DOM, the components are just an abstraction on top of Leaflet.
The components render a `<noscript>` element because React's `render()` needs to return an element, but ideally they wouldn't render anything, so using a `<div>` may be a simple workaround, but not a proper solution.
If you want to update components on the map, some of them can be updated directly by their props, if there are equivalent Leaflet setters, but otherwise the best solution is to remove the existing layer and add a new one.

In your case, I think you're trying to dynamically update the children of an element implementing `PopupContainer`, but this is not possible. To achieve this behavior, you need to remove the existing layer and add a new one, by setting a different `ref` property on the layer component.

**Comment by Oustad** [comment]
Hi,

thanks for the reply @PaulLeCam, after investigating some more in my app, and looking at the react-leaflet code I found out the problem for my part at least is as you just stated in your last reply.
So I agree that this is not a bug, but something that one must take into consideration when implementing use of popup on a map in ones application.

**Comment by PaulLeCam** [comment]
So you've found a workaround for this with your code?

I'll update the documentation to make this more explicit.

**Comment by Oustad** [comment]
Yes, I found the root cause which did the update, and I if I'm going to use popup with content coming from flux stores, it looks like I have to do as you wrote, remove the existing layer and add a new one.

**Comment by PaulLeCam** [comment]
OK perfect!
