### ISSUE TITLE
Dinamyc center property

### ISSUE THREAD

**Issue by hgenru** [PaulLeCam/react-leaflet#185]
In [docs](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/Components.md#mapcomponent) center property mark as optional. But in real world Leaflet require default center.

Next. I setup default center. Then i want change center (focus on point). I write code like this `<Map ... center={props.pointCenter || defaultCenter}/>`. And it would work, but there is one problem. If `render()` method call on next time current center reset to `defaultCenter`.

Maybe we need to create defaultProps like in [this case](https://facebook.github.io/react/docs/forms.html#controlled-components). With this logic: if first render use `defaultCenter` else use dinamyc `center` if if he is.

**Comment by hgenru** [comment]
Now I use this hack

```
        let center = this.props.center ||
        this.props.userCurrentPosition ||
        this._center ||
        defaultPosition;
        this._center = center;
```

**Comment by PaulLeCam** [comment]
Hi, 
Please follow the issue template to report an issue, preferably with an example jsfiddle or similar.

**Comment by hgenru** [comment]
https://jsfiddle.net/ofmbybbt/1/

1. Click `go to Paris` button.
2. Drag map center
3. Click `go to Paris` button again

**Comment by PaulLeCam** [comment]
Leaflet maintains its own state independently of React's one, so you need to keep track of it using the relevant events if you want your component's state to be current with the map's one.

In your case, the `center` prop that you set twice is the same as far as React is concerned, so it does not call the Leaflet setter, this is the expected behavior. You can always access the created Leaflet.Map instance using `this.leafletElement` in the Map component instance, and use it's API as you need.
