### ISSUE TITLE
[Marker] Access to the leafletElement of Marker

### ISSUE THREAD

**Issue by YUzhva** [PaulLeCam/react-leaflet#309]
### Expected behavior

When I'm creating leaflet marker like this:
```javascript
<Marker position={[marker.lat, marker.lng]}>
    <Popup>
        <span>A pretty CSS3 popup. <br/> Easily customizable.</span>
    </Popup>
</Marker>
```

Is there way to access not react component that was returned by `<Marker />`, but leafletElement that was created by marker function from leaflet.js library?

So, when I'll be using Marker as a child in my custom component like:

```javascript
<MyCustomComponent>
    <Marker position={[marker.lat, marker.lng]} />
    <Marker position={[marker.lat, marker.lng]} />
</MyCustomComponent>

// ...

class MyCustomComponent extends LayerGroup {
// ...

    this.props.children.forEach((reactLeafletMarker) => {
        // object that was created by **maker** func. imported **from leaflet**
        reactLeafletMarker.leafletElement;
    });

// ...
}
```

### Actual behavior
Currently, when I'm accessing to the child react-leaflet marker component inside MyCustomComponent:

```javascript
<MyCustomComponent>
    <Marker position={[marker.lat, marker.lng]} />
    <Marker position={[marker.lat, marker.lng]} />
</MyCustomComponent>

// ...

this.props.children.forEach((reactLeafletMarker) => {
    // react-leaflet marker component
    reactLeafletMarker;
});

// ...
```

I have available only the next object keys:

> $$typeof: Symbol(react.element)
> key: null
> props: Object
> ref: null
> type: function Marker()
> _owner: ReactCompositeComponentWrapper
> _store: Object
> _self: null
> _source: null
> __proto__: Object

Additionally to that key, I would like to have something like **leafletElement**.

### Questions about implementation
https://github.com/PaulLeCam/react-leaflet/blob/master/src/Marker.js#L30
Is it possible to assign marker to component, like:

```javascript
createLeafletElement (props: Object): Object {
    const { position, ...options } = props
    const leafletMarker = marker(position, this.getOptions(options));
    this.leafletElement = leafletMarker;
    return leafletMarker;
  }
```

So the leafletElement will be available on marker component.

**Comment by PaulLeCam** [comment]
Hi,
The `leafletElement` is already defined in the `Marker` instance (cf the [MapLayer implementation](https://github.com/PaulLeCam/react-leaflet/blob/master/src/MapLayer.js#L36)), so you can access it using the `ref` like any other element, ex:
```js
class MyComponent extends React.Component {
  bindMarker = (ref) => {
    if (ref) {
      console.log('marker element', ref.leafletElement)
    }
  }

  render () {
    return <Marker ref={this.bindMarker} {...this.props} />
  }
}
```

**Comment by YUzhva** [comment]
I need to access marker, not inside React Component that renders some map, but inside react-leaflet LayerGroup.

Markers are sending to that LayerGroup as children's.

```javascript
class MyComponent extends React.Component {
  // That is you'r example:
  bindMarker = (ref) => {
    if (ref) {
      console.log('marker element', ref.leafletElement)
    }
  }

  render () {
    return (
      <MyCustomPlugin>
        <Marker ref={this.bindMarker} {...this.props} />
        <Marker ref={this.bindMarker} {...this.props} />
      </MyCustomPlugin>
    )
  }
}

class MyCustomComponent extends LayerGroup {
  componentDidMount() {
    this.props.children.forEach((reactLeafletMarker) => {
        // that is where I need to have leafletElement
        reactLeafletMarker.leafletElement;
    });
  }
}
```

The current solution, that was proposed:
- Inside plugin (that receiving a list of react-leaflet markers) iterate through them
- On each react-leaflet marker clone that marker, with sending ref property to marker, so then ref will return leafletElement
- Push returned leafletElement to the list of leafletElements

```javascript
const listOfLeafletElements = [];

this.props.children.forEach((reactLeafletMarker) => {
  React.cloneElement(reactLeafletMarker, { ref: (marker) => {
    listOfLeafletElements.push(marker.leafletElement);
  });
});
```

Full example:
https://github.com/YUzhva/react-leaflet-markercluster/pull/16/files#diff-08e906cca00ce6702663aa1e3c2c5263R157

But that is kind of heavy solution, because each time when we receiving a list of markers, we need to iterate twice:
- One iteration is **super heavy** because it's **cloning react-component for getting marker leafletElement**.
- Another iteration, to add those markers from a leafletElements list to map.

That would be faster if Marker will have leafletElement from start, so there will be only one iteration that just adding that marker to map.

**Comment by PaulLeCam** [comment]
Sorry I don't get what you mean by "Marker will have leafletElement from start"? The Leaflet element is created by the Marker component itself when it's about to mount, that how everything else works in this library.

If your problem is getting multiple markers, no need to clone the element, you can simply adapt the `bindMarker()` handler, ex:
```js
class MyComponent extends React.Component {
  markers = []

  bindMarker = (ref) => {
    if (ref) {
      this.markers.push(ref.leafletElement)
    }
  }

  componentDidMount () {
    console.log('markers', this.markers)
  }

  render () {
    return (
      <MyCustomPlugin>
        <Marker ref={this.bindMarker} {...this.props} />
        <Marker ref={this.bindMarker} {...this.props} />
      </MyCustomPlugin>
    )
  }
}
```

If you need to access the markers before `componentDidMount()`, I don't think this will be possible directly, in that case you should create a custom component using Leaflet directly to implement the logic you want.

**Comment by YUzhva** [comment]
@PaulLeCam Notice, that `MyComponent` where you are getting `ref.leafletElement` and `< MyCustomPlugin>` - are different components.

leafletElement should be accessible inside MyCustomPlugin.

**Comment by PaulLeCam** [comment]
Yes that's the way React works, as far as I know. Seems to me the problem you're having is about accessing React instances, not the actual Leaflet element.

**Comment by YUzhva** [comment]
I'll try to record a video...

**Comment by YUzhva** [comment]
[https://youtu.be/NZdeRes-i0s](Video) - it's better to watch on speed 1.25x (=

**Comment by PaulLeCam** [comment]
Hi,
I don't think it is possible to do what you want, there seem to be some confusion between the React [elements and instances](https://facebook.github.io/react/blog/2015/12/18/react-components-elements-and-instances.html), because when you iterate over `this.props.children` from your containing component instance, you're iterating over the React elements, not the created instances. That's what refs are for, they allow to get access to the instance.

I don't know of another way than cloning the elements before rendering to dynamically inject extra props, that's the way it's done in the [`LayersControl` component](https://github.com/PaulLeCam/react-leaflet/blob/master/src/LayersControl.js#L162-L167) for example, as long as you want to use the provided `Marker`.
An alternative could be to create a custom `Marker` component that would use a context function injected by the `MarkerCluster` to notify it when it gets (un)mounted, this way it wouldn't need to clone the children.

Sorry if it's not the answer you expect, I understand the problem as I've been through it notably to implement the `LayersControl` so if there is a better way to do this I'd like to know, but it's the only one I found.

**Comment by YUzhva** [comment]
Yep...

Looks like there is not way, to make static function that will be accessible from parent component without rendering Marker )=

Thanks, for support.
