### ISSUE TITLE
Setting state for map center on onMoveend freezes the map on mobile browser

### ISSUE THREAD

**Issue by mattimononen** [PaulLeCam/react-leaflet#339]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v15.x).
- [x] Using the supported version of Leaflet (v1.x) and its corresponding CSS file is loaded.
- [x] Using the latest version of React-Leaflet.
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior

Map center should get updated without the component freezing. 

### Actual behavior

On mobile the map gets frozen after dragging the map a few times. Reproduced on two mobile devices on Chrome. Works great on desktop. 

### Steps to reproduce

Fiddle to reproduce the problem: https://jsfiddle.net/q2v7t59h/543/

**Comment by PaulLeCam** [comment]
Please open a PR with a fix if you have one but I can't reproduce the issue.

**Comment by rouzbeh** [comment]
I have encountered this problem. For some reason, moving the map via touch (as opposed to mouse on desktop or remote adb) triggers the moveend event a lot of times instead of just once. I am not sure why this happens, or even if it is due to react-leaflet.

**Comment by rouzbeh** [comment]
My best guess about what happens is: 

1- The map is moved
2- setState is called and causes the component to re-render
3- The re-rendering somehow causes the moveend event to be called again
4- Goto 1

And we overflow the stack on mobile devices. For some reason, this does not happen on desktop (chrome on mac).

**Comment by PaulLeCam** [comment]
I didn't notice at first but your jsfiddle is using an outdated version of this library, please make sure you respect the issue template instructions rather than blindly checking the boxes.

**Comment by kimmobrunfeldt** [comment]
I can confirm this is still reproducible with latest master. Chrome 47.0.2526.83, Android 4.2.2, Samsung SM-G3500 model. Trying to debug why it happens.

**Comment by kimmobrunfeldt** [comment]
I'm not sure if this fixed it, but I noticed that we were using `onMoveEnd` attribute for the Map element instead of `onViewportChanged`. Now that I changed to use `onViewportChanged`, it can't seem to get the error again. However I'm not 100% sure if this really worked, since it was sometimes hard to reproduce. Time will tell in our Sentry.io if we stop getting "Maximum call stack size exceeded" errors.

**Comment by PaulLeCam** [comment]
There is additional logic to `onViewportChange(d)` so that it doesn't get fired when the map is being updated. If you don't have similar logic in your app debouncing `onMoveEnd` in some way, or at least checking if the values changed, it's likely you get in an infinite feedback loop of having `onMoveEnd` triggered as a result of setting the position.
