### ISSUE TITLE
Use the library before v0.8.0 in browser

### ISSUE THREAD

**Issue by extend1994** [PaulLeCam/react-leaflet#384]
Hi!
I am a member of CDNJS and recently in charge of adding your library according to https://github.com/cdnjs/cdnjs/issues/11749.
I want to confirm that can the versions before v8 can be directly used in browser?
Like your UMD build after v8.
I saw there is an example index.html using `example/build/dependencies.js`, `example/build/lib.js` and `exampl/build/app.js`. But I am not sure are they kind of UMD build?

Thank you.

**Comment by PaulLeCam** [comment]
Hi!
Sounds great!

Sorry I don't get what you mean by v8? The latest version is 1.6.6, are you referring to something else?

The files produced in `example/build` are only meant to be used locally, they shouldn't be distributed. The UMD build is generated in the `dist` folder as part of the build (cf https://github.com/PaulLeCam/react-leaflet/blob/master/rollup.config.js#L14-L15), it is present in the npm package when published but not committed using git, though I can change this if it helps?

**Comment by extend1994** [comment]
Oh I am so sorry! it's a type error. Should be v0.8.0 here 😓 
So...there is no distribution before the versions v0.8.0, right?

**Comment by PaulLeCam** [comment]
I don't remember exactly at what version the UMD build was introduced, but is there any particular reason to include older versions? Why not start with the current 1.6.x and add new releases?

**Comment by extend1994** [comment]
Basically, we want to host the library as completely as possible. That's why I want to know can older versions can be directly used in front-end :)

**Comment by PaulLeCam** [comment]
OK I see, I think the first version that had the UMD build was v0.8.1. Until v1.6.0 the `dist` folder was checked out in git so the files should be available in GitHub, but since v1.6.0 the `dist` folder is only published in the npm package.
What is the process for CDNJS to get these builds and provide the new ones when available please? Is there an automatic process to do it?

**Comment by extend1994** [comment]
@PaulLeCam Thanks for your quick response! :smiley: 
Sorry for late reply... I have been busy these days. :sweat: 
CDNJS uses a mechanism called "auto-update" by setting it in `package.json` to detect new release on npm (or new tag on GitHub) and add it to CDNJS automatically. Here is the more complete doc https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md
So I think I just need to add the versions with UMD build?

**Comment by PaulLeCam** [comment]
No worries, thanks for taking care of this!
If I understand the docs correctly, I think it should be configured to get the `dist/react-leaflet.js` and `dist/react-leaflet.min.js` files from the npm packages, and yes only since version 0.8.0 of the library as previous versions didn't have an UMD build.

**Comment by extend1994** [comment]
Got! I will add it ASAP. Thank you again :)

**Comment by PaulLeCam** [comment]
Thank you!
