### ISSUE TITLE
Add PropTypes for `map` in MapLayer

### ISSUE THREAD

**Issue by vjpr** [PaulLeCam/react-leaflet#43]
I ran into an issue that was very hard to debug because this was missing.

I tried to wrap a marker in another component, and got all these crazy `findComponentRoot` errors. The issue was the map prop was not passed because it was not a direct child. Obvious issue in hindsight, but explicit props would help a lot.

**Comment by PaulLeCam** [comment]
The issue with making it an explicit prop is that React would always warn it's missing, because it checks the propTypes when creating the components tree, not when rendering it.
Because the `Map` component needs to render the `<div>` containing the map first, and then render its children, the validation happens before this `map` prop is created.

I added a [note on creating custom components](https://github.com/PaulLeCam/react-leaflet#creating-custom-components) to the Readme, hope it helps.
