### ISSUE TITLE
Unmounting Map throws exception(s)

### ISSUE THREAD

**Issue by michael-p** [PaulLeCam/react-leaflet#448]
* [X] All peer dependencies are installed: React, ReactDOM and Leaflet.
* [X] Using a supported version of React and ReactDOM (v15.x or v16.x).
* [X] Using the supported version of Leaflet (v1.3.x) and its corresponding CSS file is loaded.
* [X] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
* [X] The issue has not already been reported.
* [X] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
* [X] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

Unmounting a `Map` works, i.e. in some component
```js
render() {
  return (
    <div>
      {this.state.showMap && <Map>....</Map>}
    </div>
  );
}
```
and then toggling `this.state.showMap` should mount and unmount the Map.

### Actual behavior
It does unmount the Map but throws exception:
```
Uncaught TypeError: Cannot read property 'clearRect' of undefined
    at NewClass._clear (leaflet-src.js:12073)
    at NewClass._redraw (leaflet-src.js:12063)
```

### Steps to reproduce

This Codepen shows the issue, but interestingly with a different exception: `Cannot read property 'className' of undefined` (not sure whether that's because of codepen): https://codepen.io/anon/pen/qxYVjb?editors=0010

**Comment by PaulLeCam** [comment]
I've gone through the rabbit hole on this one and it seems to be caused by the fact the `Map` component somehow shadows the browser's `Map` when using destructuring with the UMD build, though I couldn't figure out how it happens.
In your Codepen, if you replace the first line by `const { Map: LeafletMap, TileLayer, Marker, Popup } = ReactLeaflet` and consequently `Map` by `LeafletMap`, it works as expected.

**Comment by michael-p** [comment]
Ok, that's subtle :) That explains why I got a different exception on Codepen than when testing locally. To see the original problem (why I opened this issue) add a `<Circle radius={1.0} center={[-20, 20.0]} />` to the Map and set the `preferCanvas={true}` prop on the `LeafletMap` (that's important, it works with SVG-Renderer).

I updated [the original Codepen](https://codepen.io/anon/pen/qxYVjb?editors=0010) accordingly. When unmounting the LeafletMap there is an exception in the console.

Thank you for looking into this, I appreciate it!

**Comment by PaulLeCam** [comment]
I think the issue comes from Leaflet's canvas renderer usage of `requestAnimationFrame` to defer the call to update the canvas' context, that happens at a time React has already removed the canvas from the DOM so the reference is lost.
I changed the unmounting behavior for the `Map` component in v1.8.2 so it should avoid triggering this error but that may have other unwanted side-effects, please let me know if you have any related issue.

**Comment by michael-p** [comment]
Seems to work now, thank you! I haven't noticed any problems in our App related to that change but will let you know in case I happen to find something.
