### ISSUE TITLE
Can't access state when using onEachFeature on GeoJSON component

### ISSUE THREAD

**Issue by DirkWolthuis** [PaulLeCam/react-leaflet#697]
### Expected behavior
I expect to have access to my components state variables inside the `highlightFeature` function. 

```javascript
 layer.on({
            mouseover: highlightFeature,
            mouseout: resetHighlight,
            click: clickToFeature
});
```

### Actual behavior

When calling the mouseover function called `highlightFeature`, I only have access to the inital state of my component. I guess that the layer.on function duplicates the function. When accessing a state inside `highlightFeature` function, it resolvers to a empty array, which is the default value. 

```javascript
 layer.on({
            mouseover: highlightFeature,
            mouseout: resetHighlight,
            click: clickToFeature
});
```

Is this intended?

**Comment by spenweb** [comment]
@DirkWolthuis, I am having the same issue as you are reporting. Were you able to find a fix?

**Comment by DirkWolthuis** [comment]
@spenweb I have no idea to be honest :( Never continued the project. I'm sorry.

**Comment by DirkWolthuis** [comment]
https://github.com/DirkWolthuis/fantasy-map-tool @spenweb this is the project in which I used it, maybe the answer is there.

**Comment by spenweb** [comment]
@PaulLeCam, this is still an issue. Is this intended behavior? If not, I may dive into the code to see what may be the cause.

**Comment by Shrugsy** [comment]
@spenweb As a temporary workaround, I have a hook here that alleviates the problem:  
https://gist.github.com/Shrugsy/5e898173c965e7642db8927636bedf7a

The current behaviour of the GeoJSON component is that it uses a stale closure with `onEachFeature`. Not sure exactly how far the problem extends, or how intentional it is.  

This workaround works by allowing you to create an intermediate function that always has the same reference, which will itself always call the latest version of the provided function. Then you can use the intermediate function within the `onEachFeature` callback, and it is unhindered by the stale closure keeping the reference from the initial render.  

e.g. for the initial problem in this thread, you would want to create an intermediate function like so:

```js
// define the highlightFeature function somewhere

const stableHighlightFeature = useStableCallback(highlightFeature);

// later in the 'onEachFeature' callback definition...
 layer.on({
            mouseover: highlightFeature,
            mouseout: resetHighlight,
            click: clickToFeature
});
```
