### ISSUE TITLE
V3 - Custom Layer Control / Extending Components

### ISSUE THREAD

**Issue by dylel** [PaulLeCam/react-leaflet#706]
V3 is an awesome update to the library, i've done a little bit of testing and things are looking great so far! Obviously this is early days but how will custom components work now? i.e. a custom layers control? I'm attempting to implement this and a little lost on the direction i should take, should this type of component leverage the new useMapEvent function and manage things from there?

I've read the child components section of the documentation but unsure how this would help apart from creating a ref for every layer that was added to the layer control to enable/disable each layer

**Comment by PaulLeCam** [comment]
Thanks for the early feedback!
The idea of having the `@react-leaflet/core` package is that it would provide low-level APIs (components and hooks factories) to implement specific behaviors, while the high-level APIs (components and hooks) would be exposed by the `react-leaflet` package.

Using core APIs you can't "extend" components but you can compose hooks to implement the wanted behavior.
For example the [`createControlComponent()` factory](https://github.com/PaulLeCam/react-leaflet/blob/next/packages/core/src/generic.ts#L24-L37) is a high-level way of creating a "basic" control component:

1. It defines a [`createElement()` function](https://github.com/PaulLeCam/react-leaflet/blob/next/packages/core/src/generic.ts#L28-L33) that needs to return an object satisfying the [`LeafletElement` interface](https://github.com/PaulLeCam/react-leaflet/blob/next/packages/core/src/element.ts#L10-L14)
1. This `createElement()` factory is provided to the [`createElementHook()` factory](https://github.com/PaulLeCam/react-leaflet/blob/next/packages/core/src/element.ts#L16) that is responsible for creating and keeping track of the `LeafletElement` object
1. The resulting hook is provided to the [`createControlHook()` factory](https://github.com/PaulLeCam/react-leaflet/blob/next/packages/core/src/control.ts#L7), itself responsible for the control lifecycle (adding, updating and removing)
1. Finally the [`createLeafComponent()` factory](https://github.com/PaulLeCam/react-leaflet/blob/next/packages/core/src/component.tsx#L63) is used to create the actual component, here it's a "leaf" component meaning it doesn't have children, so the implementation logic is simply to call the control hook and return `null`

You can see it used in the public API, for example with the [`AttributionControl` component](https://github.com/PaulLeCam/react-leaflet/blob/next/packages/react-leaflet/src/AttributionControl.tsx) that requires no other logic than creating Leaflet's `Control.Attribution` instance, but in more complex cases such as the [`LayersControl component`](https://github.com/PaulLeCam/react-leaflet/blob/next/packages/react-leaflet/src/LayersControl.tsx), there is additional custom logic so the lower-level factories are used rather than the higher-level `createControlComponent()` one.

Eventually all this should be documented on the website, in the meantime I hope this helps!

**Comment by dylel** [comment]
So i've left this alone for a while and its now time to revisit it. The recent documentation provides a lot of clarity however i think i'm still stuck with the approach to take on making my own control. All the examples just extend stuff that had already been written, if i wish to make a map control (i.e. something like a layers control) i wish to maintain in the react world, i.e. using JSX, state tree, my redux store etc. If i want to do this do i still have to build upon extending the original leaflet control to get my desired functionality?.

I understand that i need to do the following:

 `function createControl(props, context) {}`

-  create new instance of control
-  L.Control.extend? 
- implement
   -   onAdd - return container
   -  onRemove - return 
- use props for options like position e

`function updateControl(instance, props, prevProps) {}`

- check props for updating

And then possibly use createPathHook etc

And then using react portal to render the components children inside the instance container.


Is this still the right approach? i feel like there should be a more "react" way of creating a a custom control where i can have a single component that manages everything. This way i feel like i'll just be doing mostly everything in javascript like how the original leaflet layersControl/zoom/etc have been written but i would like to have all of this in redux like writing a normal react component if that makes any sense?. However i'm pretty sure i just don't understand some stuff, any guidance would be appreciated.

**Comment by PaulLeCam** [comment]
The goal of React Leaflet is to bring existing Leaflet features to React abstractions, but if you want to create a control directly in React rather than using existing Leaflet APIs and plugins, you shouldn't need to use all these Leaflet APIs.

I added an [example React-based control](https://react-leaflet-v3.now.sh/docs/example-react-control) that acts in a similar way to Leaflet's controls with the `position` prop by using Leaflet's CSS classes, but other than that the logic is mostly about React, hopefully that can help?
The main thing to keep in mind when building these kinds of components is what is rendered by Leaflet rather than React to avoid possibly costly re-renders. As a general rule any piece of logic that affects the map should live as close to the leaves of the tree as possible, and the `<MapContainer>` shouldn't be re-rendered, as it would create a new `Map` instance and render all its children every time.

**Comment by dylel** [comment]
Thank you so much for that awesome example, think it will really help everyone, myself included!

Just to elaborate on the logic being as close to the leaves of the tree as possible, does that mean that if i wanted to turn a layer on/off i should be using the map instance to turn the layer on/off and not using react's kinda normal way of conditional rendering to do so? because conditional rendering something would make the entire map reload?

I have a much better understanding, thank again!

**Comment by PaulLeCam** [comment]
Yes exactly, you should use the map instance as much as possible, because every time you render `<MapContainer>` it creates a new map instance. So the logic affecting the map should live in descendant components of `<MapContainer>`, not in an ancestor of it.

**Comment by dylel** [comment]
So i've got something working, not sure if i've followed the principles correctly as i'm stretching my knowledge on somethings i don't fully understand yet, i haven't really used hooks and the context api much but heres what i did to get to where i am now.

- Create react based map component (LayerControl) using your example (thanks again!)
- Copy logic from createControlledComponent and i'll be honest there's a lot of instance/context stuff i don't quite grasp yet but worked out enough to see that i could have my own context passed and props passed to addLayerToControl, which would be my map component. I used my own layerControlContext (very basic) so that i could track the layers being added with their associated props. This is my GroupedLayer
- Inside my LayerControl, access the useMap() hook to control layers

Here's a codesandbox:

[https://codesandbox.io/s/goofy-water-13hld?file=/src/LayerControl.js](url)

So in an effort to see if i did this correctly i've got some console logs on the map load and on createControlledLayer and i can see that although i don't get any map lag or anything createControlledLayer is getting called a lot. I think maybe i got to my goal but missed some understanding to the logic behind the context with layers etc and its probably just reloading all the children atm. 

Note: I haven't actually made the groups uniquely selectable, i.e. you can turn 2 base layers on at the same time

Apologies for dragging this thread on but i really do appreciate the help/insights. Thanks!

**Comment by PaulLeCam** [comment]
Sorry I don't have time to get into the specifics of your code, but if you're seeing more renders than expected I'd suggest you investigate what triggers the new renders and see if the logic can be changed to avoid these.

**Comment by cubecleveland** [comment]
@dylel can u give some hints as to how to change the code to make the base layer appear as radio boxes and actually have them rotate like in the original Layer control ?
