### ISSUE TITLE
Developing a Custom React Marker Plugin / Extension

### ISSUE THREAD

**Issue by MtthsB** [PaulLeCam/react-leaflet#771]
Dear all

I've been working on a way to enable the injection of custom react markers onto leaflet maps, as this is something that is customarily blocked or at least thwarted through the obligatory use of the ReactDom.renderToString() method in order to inject custom markers in leaflet maps. This strips the component of refs or event handlers, rendering them as pure visual representations, a watered-down version of the original jsx component.

Scrolling through many SO questions on this topic, i found various unsatisfactory approaches, some using the ReactDom.createPortal approach. But none lived up to the expectations, which is why I started to work on my own approach.

I've reached a point where I've got everything to work to my satisfaction, and I'm looking at _putting it out there_. Hence this issue.
I don't know whether this is the appropriate forum for it. On top of that I've written the code without the use of react-leaflet (due to project requirements). Nevertheless, it is setup to accommodate react components in a leaflet environment, and I think it could be either a good plugin for leaflet (independent of react-leaflet), or a good addition to react-leaflet. But I've never done this before.

My questions:
_ Do you think it's worth investigating? Do you agree it's a functionality that the community is missing?
_ How should I proceed?
_ Anyone interested in collaborating in this process? I could certainly use an experienced eye to check progress once in a while.

Warmly,

Matthias

**Comment by louisnow** [comment]
Hey Matthias, 
I've been able to implement custom Icons for the marker using L.divIcon with ReactDom.renderToString(). I'm curious to know why you need the refs or the eventHandlers on the icon itself because you would put/attach them on your custom marker or react-leaflet's Marker or Popup
Maybe I don't fully understand what it is you were trying to achieve and my solution may not be the best fit for your use case. In either case I'm curious and willing to collaborate. [React-leaflet v3](https://react-leaflet-v3.now.sh/) is almost out and I'm in the process of trying it out and it looks like it solves a lot of the problems via it's use of hooks and context.

**Comment by MtthsB** [comment]
Hi Louis

Thanks for responding. Allow me to elaborate:

Basically, I'm working on a kind of design system for my employer and we want to be able to use our own components as map markers. For example, we have buttons and cards and we want to enable our developers to use those to put together map markers that can be assembled using up to three components (e.g. a top, bottom and center component, where the center is the anchor). When using the renderToString method, you lose the default interactive behavior of the component, i.e. their hover and other pseudo states, their onclick handlers (in case of a button for example). 
On top of that, we want to _add_ functionality, e.g. when you hover on the marker, you should be able to force the top and bottom component to expand outwards from the center, thus giving the impression of the marker rising towards you.

Also, in a next stage, we want to combine this approach with the markercluster plugin.

I had the impression this was impossible with the renderToString method. Therefore, as I'm making good progress, I thought I might give back to the community ;)

Regardless, I'm looking forward to v3 and the conversion to react functional components! Keep up the good work!

**Comment by ChrisLowe-Takor** [comment]
Hi @MtthsB 

I've implemented dozens of complex and custom react-leaflet plugins using the `withLeaflet` HOC over the last few years working on https://soar.earth.  I'd argue the documentation could be improved but the actual infrastructure is fine.  It's always going to be a bit fiddly building custom react-leaflet behaviours due to the fact that both React and Leaflet want to manage their internal state and DOM tree but pretty much everything I've set out to do has been accomplishable.

In regards to your own efforts - using `ReactDom.renderToString()` is certainly the wrong approach.  It sounds like vanilla react-leaflet components can do everything you need and at worse a simple plugin.

**Comment by MtthsB** [comment]
Hello Chris

Thanks for replying, and neat project you've got there with soar.earth. I'm impressed!

With regards to the topic at hand: we are using functional components instead of class components. In my experience, this limits the extent to which you can fiddle around with (react-)leaflet. I'm now extending leaflet components and hooking into events to update my own state in order to update the react dom tree in response to changes in leaflet's dom tree. It feels kind of brittle, but it works (mostly).

In response to your assertion that vanilla react-leaflet components should actually cover my needs, I don't think that's true. Under the hood, react-leaflet's marker uses leaflet's divIcon, which does not accept jsx components as its 'html' property. That is why everyone (on SO) resorts to using renderToString or createPortal, both with their own drawbacks.

Of course, I might be wrong ;) That would be awesome, as it would make things so much easier.

Warmly

Matthias

**Comment by ChrisLowe-Takor** [comment]
@MtthsB 

Adding your own event handlers in a functional component can be done with the `useLeaflet` hook instead of the `withLeaflet` HOC.  It's the same principal.  The following is a complete example that adds it's own event handlers and also accesses the map context:

```javascript
import React, { useRef, useEffect } from 'react';
import { Marker, useLeaflet } from 'react-leaflet';

const MyMarker = () => {

    const { map } = useLeaflet()
    const markerRef = useRef();

    const myEventHandler = (e) => {
        console.log(e)
    }

    useEffect(() => {
        if (markerRef.current && map) {
            markerRef.current.on('mousemove', myEventHandler)
            map.on('mousemove', myEventHandler);
        }

        return () => {
            if (markerRef.current && map) {
                markerRef.current.off('mousemove', myEventHandler);
                map.off('mouseclick', onMapClick);
            }
        }

    }, [markerRef, map])

    return (
        <Marker
            ref={markerRef}
            position={new LatLng(0, 0)}
        />
    )
};

export default MyMarker;
```

> which does not accept jsx components as its 'html' property

Yeah this is where things get a little squirly with both React and Leaflet wanting to manage their own DOM's.   I've done something like this here: https://github.com/ChrisLowe-Takor/react-leaflet-layerlist  which allows you to render React components and JSX inside a leaflet control:

```javascript
<Map>
  <ReactLeafletLayerList>
      <MyOwnComponents />
  </ReactLeafletLayerList>
</Map>
```

The approach I took for this was to render the children with with ReactDom.createPortal but you can still use refs and internal state like Redux.

I guess the core takeaway is that react-leaflet is a wrapper around plain leaflet that bridges the gap between the two.  My general approach to building complex plugins is to construct the behaviour I want with plain leaflet then wrap up the behaviour needed on prop changes with the `updateLeaflet()` function provided with the `withLeaflet` HOC.

**Comment by MtthsB** [comment]
Yup, that confirms my suspicions. Leveraging createPortal and renderDOM is how I've gone about this, but it's still creating some hiccups that I need to deal with, e.g. in order to support myriad complex jsx markers, clustered and unclustered, on the same map and screen.

But, in order to let all this work not be in vain, I thought it could maybe become a plugin of some kind?

**Comment by ChrisLowe-Takor** [comment]
> I thought it could maybe become a plugin of some kind?

Yes. Extract all your props and pass them in through a react-leaflet plugin to the underlying leaflet plugin.  That will eliminate ReactDOM.createPortal.  This is what I did for a problem that required combining leaflet-marker-cluster, leaflet-deflate and my own custom marker/polygon hybrid.

**Comment by louisnow** [comment]
> I thought it could maybe become a plugin of some kind?

Yes, I think the community would be grateful, I'm happy to help in any way I can and I'm curious to see the approach and implementation details used in the plugin.
