### ISSUE TITLE
Decouple MapContainer from div passed to Leaflet

### ISSUE THREAD

**Issue by davetapley** [PaulLeCam/react-leaflet#833]
This is a feature request per [here](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md#features-requests), I'm happy to help work on a PR if it's likely to be approved.

---

**Background:**

I need to access the `map` instance from a distant cousin of `MapContainer` (for a side panel).

Building on the [external state docs](https://github.com/PaulLeCam/react-leaflet/blob/e2e36643150c04f190944ec638a5f267358a9ff4/packages/website/docs/example-external-state.md#L10) I can create a `Context` to expose the `map` to that sub-tree:

```
const [map, setMap] = useState<LeafletMap | undefined>(undefined)
const MapContext = createContext<LeafletMap | undefined>(map)

<MapContainer whenCreated={setMap}></MapContainer>
<MapContext.Provider value={map}>
  <SidePanel />
</MapContext.Provider>
```

Then in a sub-component of  `SidePanel` I can access the Leaflet map with:
```
const map = useContext(MapContext)
```

---

**Request:**

Using `MapContext` works, but `const map = useContext(MapContext)` looks a lot like `const map = useMap()`.

If I could instead place `MapContainer` at the parent level, and then specify the `div` to bind `Leaflet` to as a child, I think I'd be able to forego `MapContext` altogether. Something like this:

```
const mapRef = useRef<HTMLDivElement>(null)

<MapContainer mapRef={mapRef}>
    <div ref={mapRef}>
    <SidePanel />
</MapContainer>
```

This ⬆️ was inspired by ⬇️, and I _hope_ it wouldn't be too much trouble to allow `mapRef` to be passed in? 🤔 

https://github.com/PaulLeCam/react-leaflet/blob/e2e36643150c04f190944ec638a5f267358a9ff4/packages/react-leaflet/src/MapContainer.tsx#L63-L87

**Comment by PaulLeCam** [comment]
I don't want to add such feature to `MapContainer` but it's something you should be able to do with a few tweaks to the approach you've already taken:
- Implement a component similar to `MapContainer` that renders the containing `div` where you want and emits the `LeafletMap` instance
- Instead of setting only the `LeafletMap` in state, wrap it in the [`LeafletContextInterface`](https://react-leaflet.js.org/docs/core-api#leafletcontextinterface)
- Then wherever you need it, you can use the [`LeafletProvider` component](https://react-leaflet.js.org/docs/core-api#leafletprovider) from core with the `LeafletContextInterface` value, and any child component should work as expected as it gets the proper context

**Comment by alex-kowalczyk** [comment]
`MapContainer` in react-leaflet 4.1.0 exposes `map` as `ref` so the desired effect is even easier to achieve.  It would be nice to include `ref` in documentation, or even provide such a component as part of the library.

```
function MapContextOutsideProvider({children}) {
    const [context, setContext] = useState(null),
        ref = useCallback((map) => {map && setContext(createLeafletContext(map))}, [setContext]);
    return <LeafletProvider value={context}>{children(ref)}</LeafletProvider>;
}

function App() {
   <MapContextOutsideProvider>{(ref) => (
       <>
           <MapContainer ref={ref}></MapContainer>
           <Sidebar />
       </>
   )}</MapContextOutsideProvider>
}
```
