### ISSUE TITLE
React 17 Peer Dependency

### ISSUE THREAD

**Issue by DutchJelly** [PaulLeCam/react-leaflet#929]
I'm writing this issue partly as a question.

The package is using a peer dependency for react 17. However, from what I found, the package seems to work fine on react 16.8 and up. This peer dependency causes problems on most react 16 projects when using npm 8 because it'll auto-use react 17 while the rest of the packages use react 16, resulting in the app using two different react versions.

So I'm wondering
1. Why is there a peer dependency?
2. Could it just be moved to be a regular dependency?

I would suggest to use a peer dependency of `"react": "1.17.x || >1.16.8"`.

Feel free to remove this issue as I'm not following the guidelines for contributing. Thanks in advance for reading.

**Comment by PaulLeCam** [comment]
If you want to use it with React 16 it's up to you but I won't investigate any issue you might have, the library is only tested with React 17.

**Comment by marcebdev** [comment]
@PaulLeCam I would echo the above, React 16 was effectively LTS lasting from original release in 2017 and receiving a back port for one v17 change in 16.14 as well as considering that 17 is only comprised of internal changes, considered as a "stepping stone" by the React team themselves. 

While the change to 17 is "obvious" by the same logic, it's not so straightforward when you're running on a framework or in an ecosystem where there's many other dependencies involved, even with a lack of breaking changes. That's putting aside any external issues in the last 2-3yrs that may have distracted from this process. React 18 of course was a much more meaningful change but it can take time to jump an ecosystem 3-5 years into the future with a spiderweb of dependencies and it's still very new.

Given the lack of difference between 16 & 17 especially it might've made since to develop on 16.14 and verify 17 but regardless it would be nice to have the peer dependency for v3 of react-leaflet updated to officially support a peer dependency of `16.14` at least.

The current (official) solutions for many are to either use a 2yr old package (without types) or jump 5 years to update to React 18 which was just released not even 4 months ago. Given v4 is much more minor, officially having this support for v3 would go a long way.
