### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by kjartab** [PaulLeCam/react-leaflet#950]
Let me preface this issue by saying two things;

- You have done a great job making a nice react library for leaflet that is easy to use.
- I am in no way trying to argue that human rights or human rights work are unimportant or should be glossed over

With that out of the way I would like to turn the attention to the licensing move in version 3 to the Hippocratic License Version Number: 2.1. I am bit curious about your thinking behind that license change is - as I see a few issues with it:

The hippocratic license is not an open source license (btw, most react-leaflet plugins are licensed under MIT, which means they are breaking the license and thus not technically OK to use at all) and it is quite hard to use in any professional setting because;
A) it is actually quite hard to know whether or not an organization (especially big ones) you are writing applications for don't have any flaws in this regard
B) even if the organization is "nice" you would still have to spend time on discussing the licensing issue. Any legal arm of an organization would most likely shy away from software licensed in this way.

You might be of the opinion that this is exactly the type of use of your library you are trying to prohibit; orgs or devs who don't care enough about human rights to put in the extra leg work. If that is your opinion, I respect it and will leave the discussion at that.

But if the real purpose is to somehow affect the greater good in the world through software I believe there are better ways of acheiving it. The first that comes to mind is to include some funding option where some portion of the money goes towards whichever projects you feel will help improve human rights. If you are of the opinion that this would be potential "blood money" we can leave it at that. 

The reason why I'm bringing this up is that I usually end up using the same tools for recreative coding as for work. When I cannot use it for work, I will simply find something new altogether to maximize efficiency. The convenience of developers isn't particularly important in the context of human rights of couse, but seeing as I'm not sure the license serves too much of a purpose in bringing about a better world, I thought I would raise the issue anyway and see what your thoughts are on the matter.

**Comment by AZhiKai** [comment]
+1
Am encountering some legal issues at work with regards to the license for this library. It's great by the way, just that it would help if the contributors could explain the purpose of choosing this license, over open source license.

@PaulLeCam  am I able to drop you an official email to clarify the details of the license? Our legal department requires an official confirmation from you to ensure that the use of this library does not cause any legal complications in future.

**Comment by k1sul1** [comment]
I am not a lawyer. My common sense says that my use would be totally fine, but since I am not a lawyer, I cannot be sure, and I am not going to risk legal repercusions for displaying a map on a website. 

Thus I cannot use this package, and instead will have to use Leaflet.js directly. Shame, since this looked so good.

**Comment by PaulLeCam** [comment]
It's already been discussed in a previous thread when the license was adopted, please refer to the comments posted at the time.

**Comment by k1sul1** [comment]
I read the [thread](https://github.com/PaulLeCam/react-leaflet/issues/698). Weird hill to die on but you do you.

"military or related applications" have "fuck you money" at their disposal. Large corporations also have the money and resources to effectively make their own v3 based on the v2 of this package, which was MIT licenced.

Only people who are affected by this weird licence are the ones that read them in the first place. We see it and go "whoa, better find another library, this could bankrupt us." 

As someone who frequently works as a contractor for big companies who only make contracts with a clause like "the developer is responsible for any monetary loss caused by their implementation", yikes.

My company would've paid you money to get a licence I wouldn't have to lose sleep over, but since that wasn't available, I got my implementation done by other means.

**Comment by matkoniecz** [comment]
> Large corporations also have the money and resources to effectively make their own v3 based on the v2 of this package

"they will need to spend own resources to make own version instead of using my work for free" is exactly what author of this library wanted to achieve.
